# Example project registration.
#
# This file lives in projects/ (global, tracked by git).
# It is a lightweight pointer — just name and repo URL.
# All build/agent/completion config belongs in the project repo's own
# .grove/project.yaml so the project itself owns its configuration.
#
# For personal projects that you don't want to commit, run:
#   grove project create <name>
# which writes to projects.local/ (git-ignored).
#
# Then start an agent instance on a branch:
#   grove start example_project feat/my-feature

name: example_project
repo: git@github.com:example/example_project.git
