# Example project definition.
#
# This file lives in projects/ (global, tracked by git).
# Fork this repo and edit or add projects here to share them with your team.
#
# For personal projects that you don't want to commit, run:
#   grove project create <name>
# which writes to projects.local/ (git-ignored).
#
# Then start an agent instance on a branch:
#   grove start example_project feat/my-feature

name: example_project
repo: git@github.com:example/example_project.git

bootstrap:
  - npm install

agent:
  command: claude
  args: []

dev:
  start:
    - npm run dev

# complete: commands run when you call `grove finish <id>`.
# They execute inside the worktree. Use {{branch}} for the branch name.
# Uncomment and adapt the steps you want.
complete:
  # Push the branch to the remote.
  - git push -u origin {{branch}}

  # Open a pull request (requires GitHub CLI: https://cli.github.com).
  # - gh pr create --title "{{branch}}" --fill

  # Or go straight to merge — squash into main and delete the branch.
  # - gh pr create --title "{{branch}}" --fill && gh pr merge --squash --delete-branch
